In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
print(a*2)
print(a+3)
print(a-2)

[0 2 4 6 8]
[3 4 5 6 7]
[-2 -1  0  1  2]


In [4]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [5]:
print(a-b*2)
print(a+b)

[-2. -1.  0.  1.  2.]
[1. 2. 3. 4. 5.]


In [8]:
# these operations are faster in numpy than pure python

a = np.arange(100_000)
%timeit a+2

73.1 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
# in native python
a = range(100_000)
%timeit [i+2 for i in a]

8.85 ms ± 223 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Array Multiplication

#### 1-D array

In [10]:
a = np.random.randint(1, 10, 5)
a

array([5, 3, 8, 1, 5])

In [11]:
b =np.random.randint(1, 10, 5)
b 

array([4, 6, 5, 4, 1])

In [12]:
a * b  # elementwise operations

array([20, 18, 40,  4,  5])

#### 2-D array

In [13]:
a = np.random.randint(1, 10, (2,3))
a

array([[4, 2, 4],
       [4, 8, 7]])

In [14]:
b = np.random.randint(1, 10, (2,3))
b

array([[6, 7, 8],
       [5, 5, 1]])

In [15]:
a * b  # element wise multiplication

array([[24, 14, 32],
       [20, 40,  7]])

In [16]:
# a.dot(b) this will throw an error as Matix multiplication is not possible here

In [17]:
a.dot(b.T)   # b.T will transpose the 2,3 matrix to 3,2 matrix

array([[ 70,  34],
       [136,  67]])

#### Comparison

In [18]:
a = np.array([1, 3, 7, 6, 5])
b = np.array([1, 2, 7, 8, 5])

print(a,b)

[1 3 7 6 5] [1 2 7 8 5]


In [19]:
# Comparison
a == b

array([ True, False,  True, False,  True])

In [20]:
a > b

array([False,  True, False, False, False])

#### Arraywise Comparison

In [21]:
a = np.array([1,2,3,4])
b = np.array([3,4, 9, 8])
c = np.array([1,2,3,4])

In [22]:
np.array_equal(a, b)

False

In [23]:
np.array_equal(a, c)

True

#### Logical Operations

In [24]:
a = np.array([1,1,0,0], dtype='bool')
b = np.array([1,0,1,0], dtype='bool')

print(a, b)

[ True  True False False] [ True False  True False]


In [25]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [26]:
np.logical_and(a,b)

array([ True, False, False, False])

#### Adv mathematics func

In [27]:
a = np.array([1, 0.5, 0, 3])
a

array([1. , 0.5, 0. , 3. ])

In [28]:
np.sin(a)

array([0.84147098, 0.47942554, 0.        , 0.14112001])

In [29]:
np.log(a)

<ipython-input-29-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([ 0.        , -0.69314718,        -inf,  1.09861229])

In [34]:
np.pi

3.141592653589793

In [35]:
np.sin(np.pi/2)

1.0

In [36]:
np.exp(a)

array([ 2.71828183,  1.64872127,  1.        , 20.08553692])

In [37]:
a = np.triu(np.ones((3, 3)), 1)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [38]:
a.T  # transposition of array is just a view and stored in memory

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

#### Counting Sums

In [39]:
x = np.array([1,2,3,4])
x.sum()

10

In [40]:
x = np.array([[1,2,3],[3,4,5]])
x

array([[1, 2, 3],
       [3, 4, 5]])

In [41]:
x.sum(axis=0)  # column sum

array([4, 6, 8])

In [42]:
x.sum(axis=1)  # row sum

array([ 6, 12])

#### Other functions

In [43]:
x.min()

1

In [44]:
x.min(axis=1)

array([1, 3])

In [45]:
x.max(axis=0)

array([3, 4, 5])

In [46]:
x.argmin()  # index of min element

0

In [47]:
x.argmax()  # index of max element

5

#### Logical Operations

In [48]:
np.all([True, False, True])

False

In [49]:
np.any([True, False, True])

True

In [50]:
a = np.zeros((10,10))
np.any(a)

False

In [51]:
np.all(a)

False

In [52]:
np.all(a==0)

True

In [53]:
np.any(a!=0)

False

#### Stats

In [54]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

print(x, "\n\n",y)

[1 2 3 1] 

 [[1 2 3]
 [5 6 1]]


In [55]:
x.mean()

1.75

In [56]:
np.median(x)

1.5

In [57]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [58]:
x.std()

0.82915619758885

#### broadcasing

In [59]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
a[2:,2:]=0
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 0., 0.]])

In [53]:
a = np.arange(0, 40, 10)
a.shape

(4,)

#### newaxis

In [62]:
a = a[:, np.newaxis]   # newaxis is a nice feature supported by numpy
a

array([[[[1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.]]],


       [[[1., 1., 0., 0.]]]])

In [63]:
a.shape

(3, 1, 1, 4)

In [64]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544,1913, 2448])

In [65]:
distance = np.abs(mileposts - mileposts[:, np.newaxis])
distance

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [66]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]

print(x, "\n\n", y)

[0 1 2 3 4] 

 [[0]
 [1]
 [2]
 [3]
 [4]]


In [67]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

the numpy.ogrid function allows to directly create vectors x and y of the previous example, with two
"significant dimensions":

In [68]:
x, y = np.ogrid[0:5, 0:5]

print(x, "\n\n", y)

[[0]
 [1]
 [2]
 [3]
 [4]] 

 [[0 1 2 3 4]]


In [69]:
print(x.shape, y.shape)

(5, 1) (1, 5)


In [70]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

np.mgrid
directly providesmatrices full of indices for cases where we can’t (or don’t want to) benefit frombroadcasting

In [71]:
x, y = np.mgrid[0:4, 0:4]
print(x, "\n\n", y)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]] 

 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


#### Flattening the array
Higher dimensions: last dimensions ravel out “first”.

In [72]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [74]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

#### Reshaping
reshaping may return view or copy, so use caustiously

In [75]:
a.shape

(2, 3)

In [76]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [77]:
a.ravel().reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
a.reshape((2, -1))   # # unspecified (-1) value is inferred

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
a.reshape((3, -1))

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Adding a dimention

In [80]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [81]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3]])

In [82]:
a[np.newaxis,:]

array([[0, 1, 2, 3]])

#### Dimension shuffling

In [83]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [84]:
a.shape

(4, 3, 2)

In [85]:
a[0,1,0]

2

In [86]:
a.ravel().reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### Resizing

In [89]:
o = np.arange(4)
o.resize((8,))
o

# It will throw an error 
# ValueError: cannot resize an array that references or is referenced
# by another array in this way.  Use the resize function

array([0, 1, 2, 3, 0, 0, 0, 0])

#### Sorting data

In [90]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [91]:
b = np.sort(a, axis=1)  # Sorts each row separately!
b

array([[3, 4, 5],
       [1, 1, 2]])

In [92]:
a.sort(axis=1)  # inplace sort
a

array([[3, 4, 5],
       [1, 1, 2]])

In [93]:
# Sorting with fancy indexing:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [94]:
a[j]

array([1, 2, 3, 4])

In [95]:
# Finding minima and maxima
j_max = np.argmax(a)
j_min = np.argmin(a)

print(j_max, j_min)  # indexes
print(a[j_max], a[j_min])

0 2
4 1
