In [1]:
import numpy as np

### Arrays

In [2]:
# numpy array
arr = np.array([0,1,2,3])
arr

array([0, 1, 2, 3])

numpy calc is faster than native python 

In [3]:
# testing the same

L = range(100000)
%timeit [i**2 for i in L]

37.6 ms ± 126 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
L = np.arange(100000)
%timeit L**2

106 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


there are so many ways to create array in numpy, we will see them one by one
#### starting with 1-D array

In [5]:
a = np.array([1,2,5,3,5,9])
a

array([1, 2, 5, 3, 5, 9])

In [6]:
a = np.arange(1, 20)    # start, end
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [7]:
a = np.arange(1, 20, 3)   # start, end, step
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
# check dimension and size
print("dimension - ", a.ndim)
print("size - ", a.shape)
print("length - ", len(a))

dimension -  1
size -  (7,)
length -  7


#### 2-D array

In [9]:
b = np.array([[1,2,3], [2,3,4], [3,4,5]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [10]:
# check dimension and size
print("dimension - ", b.ndim)
print("size - ", b.shape)
print("length - ", len(b))

dimension -  2
size -  (3, 3)
length -  3


3-D array

In [11]:
c = np.array([[[5,7], [8,9], [0,7]], [[1,2], [2,3], [6,7]], [[5,7], [8,9], [0,7]]])
c

array([[[5, 7],
        [8, 9],
        [0, 7]],

       [[1, 2],
        [2, 3],
        [6, 7]],

       [[5, 7],
        [8, 9],
        [0, 7]]])

In [12]:
# check dimension and size
print("dimension - ", c.ndim)
print("size - ", c.shape)
print("length - ", len(c))

dimension -  3
size -  (3, 3, 2)
length -  3


Simplest way to create test array

In [13]:
# by no
a = np.arange(1, 10, 2)
print(a)
print(a.shape)

[1 3 5 7 9]
(5,)


In [17]:
# by number of points
a = np.linspace(1, 21, 6)  # pick 6 no between 1 to 20 including (equally spaced)
print(a)
print(a.shape)

[ 1.  5.  9. 13. 17. 21.]
(6,)


In [18]:
# by number of points
a = np.linspace(1, 21, 6, endpoint=False)  
print(a)
print(a.shape)

[ 1.          4.33333333  7.66666667 11.         14.33333333 17.66666667]
(6,)


Common arrays to use :

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Random no generation 
with help of numpy random library

In [24]:
np.random.rand(5)   # pick any 5 value between 0 and 1

array([0.45968392, 0.21417371, 0.40686862, 0.20202221, 0.45988607])

In [25]:
np.random.randn(5)  # includes negative no as well (Gaussian)

array([-0.01539544, -0.80194135,  0.05788418, -0.03613102,  1.2058106 ])

In [26]:
np.random.randint(9)  # this will pick any random no from 0 to 8 (integer)

6

In [27]:
np.random.randint(10, 13)  # start, end    end exclusive

10

In [28]:
np.random.randint(10, 13, 2)  # start, end, no of element    end exclusive

array([12, 12])

In [29]:
np.random.randint(10, 13, 4)  # start, end, no of element    end exclusive

array([10, 12, 11, 11])

In [30]:
np.random.randint(1, 20, (4, 3))

array([[15,  5,  4],
       [17,  9, 12],
       [ 6,  8, 10],
       [14, 18,  6]])

If you set the np.random.seed(a_fixed_number) every time you call the numpy's other random function, the result will be the same:

In [31]:
np.random.seed(123)
np.random.randint(1, 10, 2)

array([3, 3])

In [32]:
np.random.seed(123)
np.random.randint(1, 10, 2)

array([3, 3])

#### Data Type

In [33]:
a = np.random.randint(3,9, 3)
print(a)
print(a.dtype)

[4 6 5]
int32


In [34]:
a = np.random.rand(3)
print(a)
print(a.dtype)

[0.42310646 0.9807642  0.68482974]
float64


You can explicitly specify which data-type you want:

In [35]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

In [36]:
c = np.array([1, 2, 3])
c.dtype

dtype('int32')

In [37]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

In [38]:
# complex data type
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

In [39]:
# Boolean
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

In [40]:
# String
f = np.array(['Bonjour', 'Hello', 'Hallo'])
f.dtype  # unicode string with max 7 letters

dtype('<U7')

### Indexing and Slicing

In [41]:
a = np.arange(10)
print(a)

a[2], a[0], a[8], a[-1]

[0 1 2 3 4 5 6 7 8 9]


(2, 0, 8, 9)

In [42]:
a[2:7]

array([2, 3, 4, 5, 6])

In [43]:
# reversing the array
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
a[1:8:3]  #start, end, step

array([1, 4, 7])

In [45]:
a[:4]  #start, 4

array([0, 1, 2, 3])

In [46]:
a[6:]  #6, end

array([6, 7, 8, 9])

In [47]:
a[:]  #start, end

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy array supports all python Indexing and Slicing operation
#### Numpy indexing and Slicing

In [48]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a[5:] = 11
a

array([ 0,  1,  2,  3,  4, 11, 11, 11, 11, 11])

In [50]:
a[6:] = a[::-1][6:]
a

array([ 0,  1,  2,  3,  4, 11,  3,  2,  1,  0])

### Array Copies and Views

In [51]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b = a[6:]
b

array([6, 7, 8, 9])

In [53]:
a[7] =  13
print(a)
print(b)

[ 0  1  2  3  4  5  6 13  8  9]
[ 6 13  8  9]


In [54]:
print(np.may_share_memory(a,b))

True


#### Copy

In [55]:
b = a[6:].copy()
b

array([ 6, 13,  8,  9])

In [56]:
a[8] =  16
print(a)
print(b)

[ 0  1  2  3  4  5  6 13 16  9]
[ 6 13  8  9]


In [57]:
print(np.may_share_memory(a,b))

False


#### Boolean indexing or Fancy indexing

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b = a%3==0
b   # boolean array

array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [60]:
# picking only those for which a%3==0 is TRUE
a[b]   # boolean indexing

array([0, 3, 6, 9])

In [61]:
a[b] = a[b]+200
a

array([200,   1,   2, 203,   4,   5, 206,   7,   8, 209])

In [62]:
b = np.random.randint(0, 6, 3)
b

array([1, 0, 0])

In [63]:
a[b]

array([  1, 200, 200])